import { ContentSectionItem } from "./content-section-item";

export class ContentItem {
  parentId: string;
  id: string;
  alias: string;
  module: string;
  type: string;
  createdBy: string;
  createdDate: string;
  createdDateTicks: number;
  updatedBy: string;
  updatedDate: string;
  updatedDateTicks: number;
  name: string;
  sectionItems: string;
  content: string;
  htmlContent: string;
  snippet: string;
  attribute01: string;
  attribute02: string;
  attribute03: string;
  attribute04: string;
  attribute05: string;
  attribute06: string;
  attribute07: string;
  attribute08: string;
  attribute09: string;
  attribute10: string;
  attribute11: string;
  attribute12: string;
  attribute13: string;
  attribute14: string;
  attribute15: string;
  attribute16: string;
  attribute17: string;
  attribute18: string;
  attribute19: string;
  attribute20: string;
  contentSectionItems: ContentSectionItem[];
  childCount: number;
}
